name: Detailed PageSpeed Report
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pagespeed-report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Detailed PageSpeed Report
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://mishrashubham.online  # Replace with your target URL
