name: GitHub-Profile-3D-Contribution

on:
  schedule: # every 12 hours
    - cron: "11 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    environment: portfolio  # Specify your environment name here
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email f10.shubham@gmail.com
          git add -A .
          git commit -m "GitHub 3D Profile"
          git push
